### ISSUE TITLE
Allow custom reporters

### ISSUE THREAD

**Issue by flashbackzoo** [mucsi96/nightwatch-api#217]
## Expected Behavior

I would like to use a custom reporter, for example [nightwatch-html-reporter](https://www.npmjs.com/package/nightwatch-html-reporter), but this is not currently possible.

## Current Behavior

The `createSession` method creates a reporter when instantiating a client.

https://github.com/mucsi96/nightwatch-api/blob/cf3262698271cbe532b980255b919ad3426bd35e/packages/nightwatch-api/src/client.ts#L82

There is no way to inject a custom reporter.

## Possible Solution

Nightwatch allows users to provide a [global reporter](https://github.com/nightwatchjs/nightwatch-docs/blob/master/guide/using-nightwatch/external-globals.md#global-reporter).

Allow users to provide a reporter via `nightwatch.conf.js` for example:

```js
const customReporter = () => {};

module.exports = {
  test_settings: {
    reporter: customReporter,
  },
};
```

`test_settings` is available in `createSession`, so could check if a custom reporter is present, and fall back to using the default reporter.

## Environment

* nightwatch: 1.0.19
* nightwatch-api: 2.1.1

**Comment by mucsi96** [comment]
Hi @flashbackzoo! Thanks for you feedback! I am not sure that this is possible, because the main goal of this package is to separate the "runner" from the "client" and give the users a promise based client they can use with any test runner. Also they can use it without runner as well (take a screenshot of a website or scrape some data from it) Updating the internal objects of Nightwatch test runner and call the proper reporter methods is not something we can do here. Event if you would be able to pass a custom reporter it would not work as expected as testcase and testsuite related parts of Nightwatch are omitted when you are using this package. You should search a reporter for the runner you are using. If that's for example Cucumber then use some Cucumber reporter. Like Cucumber HTML reporter. I have created an issue for documenting this. https://github.com/mucsi96/nightwatch-api/issues/226. Closing this issue for now

**Comment by flashbackzoo** [comment]
Thanks @mucsi96, makes sense. I'll try a Cucumber reporter and see if I can contribute some docs to https://github.com/mucsi96/nightwatch-api/issues/226

**Comment by mucsi96** [comment]
Awesome!
