### ISSUE TITLE
how to configure retries of failing e2e tests

### ISSUE THREAD

**Issue by Qvatra** [mucsi96/nightwatch-api#553]
is there a way to configure retries of failing e2e tests?
something like `--retries <n>` that exists in nightwatch cli

**Comment by spnraju** [comment]
Hi @Qvatra , Thank you for raising the issue. I believe this is something which should be part of cucumberjs rather than nightwatch-api. I hope you understand the reason. There seems to be some discussion around this in the below threads. You may want to take a look. Please let us know if you need any further help. Kindly close this issue if you got the info you are looking for.

https://github.com/cucumber/cucumber-js/issues/727
https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#rerun-separator

**Comment by Qvatra** [comment]
indeed was able to implement retry by using this:
https://github.com/cucumber/cucumber-js/issues/727#issuecomment-453076517
